import "@/styles/globals.css";
import ToastContainers from "@/components/common/Toast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DB({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
