import "@/styles/globals.css";
import Headers from "@/components/common/Header/Header";

export const metadata = {
  title: "Blog page || Zobaidul Kazi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Headers />
        {children}
      </body>
    </html>
  );
}
