openapi: 3.0.0
info:
  title: Blog API
  description: API documentation for managing blog posts
  version: 1.0.0
paths:
  /blogs:
    get:
      summary: Get all blogs
      responses:
        '200':
          description: A list of blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
    post:
      summary: Create a new blog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogInput'
      responses:
        '201':
          description: Blog created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
components:
  schemas:
    Blog:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the blog post
        title:
          type: string
          description: The title of the blog post
        desc:
          type: string
          description: The description of the blog post
        img:
          type: string
          description: The image URL of the blog post
        href:
          type: string
          description: The URL link of the blog post
        createdAt:
          type: string
          format: date-time
          description: The timestamp when the blog post was created
        updatedAt:
          type: string
          format: date-time
          description: The timestamp when the blog post was last updated
    BlogInput:
      type: object
      required:
      - title
      - desc
      - img
      - href
      properties:
        title:
          type: string
          description: The title of the blog post
        desc:
          type: string
          description: The description of the blog post
        img:
          type: string
          description: The image URL of the blog post
        href:
          type: string
          description: The URL link of the blog post
