export const keywords = [
  "Zobaidul Kazi",
  "zobaidulkazi",
  "zobkazi",
  "Zobkazi",
  "Md Zobaidul Kazi",
  "Md Zobaidul Islam Kazi",
  "Zobaidul Islam Kazi",
  "Software Developer",
  "Mechanical Engineer",
  "Mechanical Design",
  "Mechanical Engineering",
  "Fullstack Developer",
  "React JS",
  "Next JS",
  "Tailwind CSS",
  "Node JS",
  "Mongo DB",
  "Express JS",
  "Docker",
  "PostgreSQL",
  "Redis",
  "TypeScript",
  "JavaScript",
  "React Native",
  "Flutter",
  "Kafka",
  "RabbitMQ",
  "Microservices",
  "API Documentation",
  "Postman",
  "Swagger",
  "Markdown",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Confluence",
  "Notion",
  "Slack",
  "Trello",
  "Asana",
  "ERP Application Developer",
  "Mongoose",
  "Zustand",
  "API Integration",
  "REST API",
  "GraphQL",
  "Microservices Architecture",
  "CI/CD",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "SolidWorks",
  "AutoCAD",
  "Software Solutions",
  "Kazibyte",
  "Innovative Solutions",
  "Frontend Developer",
  "Backend Developer",
  "Database Design",
  "Cloud Deployment",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Digital Ocean",
  "Heroku",
  "Agile Methodology",
  "Scrum",
  "Software Development",
  "Mechanical Solutions",
  "Pug Templating",
  "Portfolio Website",
  "Dhaka Developer",
  "Bangladesh Developer",
  "Custom Software Development",
  "Responsive Web Design",
  "UI/UX Design",
  "Technical Documentation",
  "Deno",
  "Hono Framework",
  "Email Templates",
  "Mongoose ODM",
  "MailHog Testing",
  "Authentication Service",
  "Blockchain Technology",
  "API Security",
  "Software Engineering"
];
