export { default as FacebookIcon } from "./FacebookIcon";
export { default as GitHubIcon } from "./GitHubIcon";
export { default as LinkedInIcon } from "./LinkedInIcon";
export { default as XIcon } from "./XIcon";
export { default as TelegramIcons } from "./TelegramIcons";
export { default as InstagramIcon } from "./InstagramIcon";
export { default as WhatsappIcon } from "./WhatsappIcon";
export { default as DiscordIcon } from "./DiscordIcon";
export { default as SwaggerIcon } from "./SwaggerIcon";
