import "@/styles/globals.css";
import ToastContainers from "@/components/common/Toast";
import { Theme } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/components/ui/dashboard/AuthContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">
          <Theme>
            <ToastContainers />
            <AuthProvider>{children}</AuthProvider>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
